In [32]:
%%html
<h1 align="center"> <font color="red"> Análise de Dados Epidêmicos - Dengue </h1>
<h2 align="center"> <font color="blue"> Aluno: Marcio Colazingari </h2> <br>
    <p align="center"><img src="dados/dengue_animado.gif"></p>
<br>
<h2 align="center"> <font color="green"> Trabalho de Entrega do Curso Enap BootCamp </h2>
<h2 align="center"> Módulo 2 - Ciência de Dados </h2>
<h2 align="center"> Professor: Professor: Alex Lopes </h2> <br>
<h3 align="center"> <font color="brown"> 2020, Escola Nacional de Administração Pública - Enap </h3>

In [39]:
%%html
<h3> O objetivo deste trabalho será a Análise de Dados sobre a epidemia de dengue em 2 cidades da América Latina.</h3>
<h3> Tratam-se de dois(02) arquivos no formato CSV contendo dados extraídos do sítio da internet: </h3>
<a href="https://www.drivendata.org/" align="center" target="popup"><h2> <img src="dados/drivendata-logo.svg", width="400"> </h2> </a>
<br>

In [23]:
%%html
<h2><font color="red"> Dos dados: </h3> </font>
<h3> Foram fornecidos dois arquivos CSVs contendo:<br>
    1. informações climáticas e de geolocalização ; <br>
    2. quantitativos do espalhamento da doença.</h3>
<h3 align="left"><font color="blue"> Os dados serão analisados <br> com o uso de bibliotecas aprendidas no curso.<br>
<font color="green"> 1. <font color="red"> Pandas e Numpy <font color="green"> para a organização dos dados <br>
2. <font color="green">  <font color="red ">Matplotlib e Seaborn para a <font color="green"> geração de gráficos.

In [2]:
# Importação das bibliotecas
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [1]:
%%html
<h2 align="center"> <font color = blue> Carregamento e preparação dos Dados CSVs </h2>

In [48]:
# loading do CSV de features e labels e merge dos dados:
df_features = pd.read_csv("dados/dengue_features_train.csv", na_values=[" ","...","na","NA","nan","Na"])
df_labels = pd.read_csv("dados/dengue_labels_train.csv",na_values=[" ","...","na","NA","nan","Na"])
df_dengue = pd.merge(df_features,df_labels)
df_dengue

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm,total_cases
0,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0,4
1,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6,5
2,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4,4
3,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0,3
4,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1451,iq,2010,21,2010-05-28,0.342750,0.318900,0.256343,0.292514,55.30,299.334286,...,88.765714,55.30,18.485714,9.800000,28.633333,11.933333,35.4,22.4,27.0,5
1452,iq,2010,22,2010-06-04,0.160157,0.160371,0.136043,0.225657,86.47,298.330000,...,91.600000,86.47,18.070000,7.471429,27.433333,10.500000,34.7,21.7,36.6,8
1453,iq,2010,23,2010-06-11,0.247057,0.146057,0.250357,0.233714,58.94,296.598571,...,94.280000,58.94,17.008571,7.500000,24.400000,6.900000,32.2,19.2,7.4,1
1454,iq,2010,24,2010-06-18,0.333914,0.245771,0.278886,0.325486,59.67,296.345714,...,94.660000,59.67,16.815714,7.871429,25.433333,8.733333,31.2,21.0,16.0,1
1455,iq,2010,25,2010-06-25,0.298186,0.232971,0.274214,0.315757,63.22,298.097143,...,89.082857,63.22,17.355714,11.014286,27.475000,9.900000,33.7,22.2,20.4,4

In [53]:
%%html
<h2 align="center"> <font color = "red"> Dicionário dos dados </font> </h2> 
<font color = "blue"><h3> NDVI (ne,nw,se,sw) - <font color = "gray"> Índice de Vegetação da Diferença Normalizada (-1 planta morta +1 planta saudável ) </h3> 
<font color = "blue"><h3> Preciptation_amt - <font color = "gray"> Preciptação Total </h3>
<font color = "blue"><h3> reanalilysis_air_temp_k - <font color = "gray"> Temperatura do Ar (mean) </h3>
<font color = "blue"><h3> reanalysis_avg_temp_k - <font color = "gray"> Temperatura do ar (avg) </h3>
<font color = "blue"><h3> reanalysis_dew_point_temp_k - <font color = "gray"> Temperatura do ponto de orvalho </h3>
<font color = "blue"><h3> reanalysis_relative_humidity_percent - <font color = "gray"> Umidade Relativa do Ar (mean) </h3>
<font color = "blue"><h3> reanalysis_tdtr_k - <font color = "gray"> Faixa da Temperatura Diurna </h3>
<font color = "blue"><h3> station_diur_temp_rng_c - <font color = "gray"> Faixa de temperatura medidas da estação climática </h3>
<font color = "blue"><h3> total_cases - <font color = "gray"> Casos de Cotaminação Totais </h3>